In [1]:
import numpy as np

In [38]:
my_list=[1,2,3]
print(my_list)
my_array=np.array(my_list)
my_array.shape

[1, 2, 3]


(3,)

In [39]:
my_matrix=[my_list,my_list,my_list]
print(my_matrix)
my_array2=np.array(my_matrix)
my_array2.shape

[[1, 2, 3], [1, 2, 3], [1, 2, 3]]


(3, 3)

In [40]:
my_3matrix=[my_matrix,my_matrix,my_matrix]
print(my_matrix)
my_array3=np.array(my_3matrix)
my_array3.shape

[[1, 2, 3], [1, 2, 3], [1, 2, 3]]


(3, 3, 3)

In [16]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [18]:
np.zeros(3)

array([0., 0., 0.])

In [21]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
np.ones(3)

array([1., 1., 1.])

In [23]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [2]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [3]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [4]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [16]:
np.random.rand(2)

array([0.02669148, 0.10740776])

In [72]:
d=np.random.rand(3,3)
d

array([[0.9071001 , 0.60120996, 0.87862237],
       [0.19375127, 0.54466013, 0.73198895],
       [0.36020759, 0.1690242 , 0.49263681]])

In [29]:
np.random.randn(2)

array([-0.33525312,  1.18720444])

In [32]:
np.random.randn(3,3)

array([[-0.06981369, -0.14295703,  0.83494984],
       [ 1.16043943, -0.98246723, -0.78546664],
       [ 0.73468277, -1.53918734,  0.50976241]])

In [35]:
np.random.randint(1,20)
#(start,stop)

14

In [37]:
np.random.randint(1,20,5)
#(start,stop,number of samples)

array([ 3,  4,  7, 12, 16])

In [48]:
my_array_ex=np.arange(1,26,1)
my_array_ex
my_array_ex.shape

(25,)

In [55]:
a=my_array_ex.reshape(25,1)
b=my_array_ex.reshape(5,5)
c=my_array_ex.reshape(1,25)
print(a)
print(b)
print(c)

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]
 [24]
 [25]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
  25]]


In [66]:
b.max()

25

In [67]:
b.min()

1

In [68]:
b.argmax()

24

In [69]:
b.argmin()

0

In [77]:
print('array b adalah',b.dtype)
print('array d adalah',d.dtype)

array b adalah int64
array d adalah float64


In [79]:
i = np.arange(0,30,1)
i

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [80]:
i[8]

8

In [81]:
i[5:13]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [82]:
i[0:20:3]

array([ 0,  3,  6,  9, 12, 15, 18])

In [84]:
i[0:4] = 33
i

array([33, 33, 33, 33,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [86]:
i = np.arange(0,30,1)
slice_of_array=i[0:12]
slice_of_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [90]:
slice_of_array[:]=66
print(slice_of_array)
print(i)

[66 66 66 66 66 66 66 66 66 66 66 66]
[66 66 66 66 66 66 66 66 66 66 66 66 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


In [91]:
i = np.arange(0,30,1)
array_copy = i.copy()
array_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [92]:
i[5:10]=99
print(i)
print(array_copy)

[ 0  1  2  3  4 99 99 99 99 99 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


In [98]:
print(b)
print(b[1])     #a way to get array in same row number (1)
print(b[2][1])  #a way to get individual value
print(b[2,1])   #another way to get individual value

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[ 6  7  8  9 10]
12
12


In [103]:
print(b)
print(b[:2])     #printing array from row 0 and row 1
print(b[:,1:])   #printing array from column 1 until 4 (end)
print(b[:2,1:])  #printing array with coordinates row (0-1) and coordinates column(1-4)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 2  3  4  5]
 [ 7  8  9 10]
 [12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]
[[ 2  3  4  5]
 [ 7  8  9 10]]


In [113]:
print(a)
print([a[3],a[6],a[9]])     #fancy indexing 1d array
print(a[[3,6,9]])           #fancy indexing 1d array, another way


[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]
 [24]
 [25]]
[array([4]), array([7]), array([10])]
[[ 4]
 [ 7]
 [10]]


In [115]:
print(b)
print([b[[2,4]]])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[array([[11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25]])]


In [123]:
arr=np.arange(5,25,2)
print(arr)
print(arr>15)
bool_arr = arr>15
print([bool_arr])
print([arr[bool_arr]])
x=13
print([arr[arr<x]])

[ 5  7  9 11 13 15 17 19 21 23]
[False False False False False False  True  True  True  True]
[array([False, False, False, False, False, False,  True,  True,  True,
        True])]
[array([17, 19, 21, 23])]
[array([ 5,  7,  9, 11])]
