In [40]:
import numpy as np
import pandas as pd
array=np.arange(30,300,30)
array

array([ 30,  60,  90, 120, 150, 180, 210, 240, 270])

In [6]:
array+1

array([ 31,  61,  91, 121, 151, 181, 211, 241, 271])

In [7]:
1/array

array([0.03333333, 0.01666667, 0.01111111, 0.00833333, 0.00666667,
       0.00555556, 0.0047619 , 0.00416667, 0.0037037 ])

In [10]:
array*array

array([  900,  3600,  8100, 14400, 22500, 32400, 44100, 57600, 72900])

In [11]:
array2d=array.reshape(3,3)
array2d

array([[ 30,  60,  90],
       [120, 150, 180],
       [210, 240, 270]])

In [12]:
array2d**2

array([[  900,  3600,  8100],
       [14400, 22500, 32400],
       [44100, 57600, 72900]])

In [13]:
array2=[1,2,3]
array2d*array2

array([[ 30, 120, 270],
       [120, 300, 540],
       [210, 480, 810]])

In [14]:
array2d/array2d

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
np.sqrt(array2d)

array([[ 5.47722558,  7.74596669,  9.48683298],
       [10.95445115, 12.24744871, 13.41640786],
       [14.49137675, 15.49193338, 16.43167673]])

In [16]:
np.exp(array2d)

array([[1.06864746e+013, 1.14200739e+026, 1.22040329e+039],
       [1.30418088e+052, 1.39370958e+065, 1.48938420e+078],
       [1.59162664e+091, 1.70088776e+104, 1.81764939e+117]])

In [17]:
np.sin(array2d)

array([[-0.98803162, -0.30481062,  0.89399666],
       [ 0.58061118, -0.71487643, -0.80115264],
       [ 0.46771852,  0.94544515, -0.17604595]])

In [18]:
np.cos(array2d)

array([[ 0.15425145, -0.95241298, -0.44807362],
       [ 0.81418097,  0.69925081, -0.59846007],
       [-0.88387747,  0.32578131,  0.98438195]])

In [19]:
np.tan(array2d)

array([[-6.4053312 ,  0.32004039, -1.99520041],
       [ 0.71312301, -1.02234624,  1.33869021],
       [-0.52916669,  2.90208535, -0.17883906]])

In [22]:
np.log(array2d)

array([[3.40119738, 4.09434456, 4.49980967],
       [4.78749174, 5.01063529, 5.19295685],
       [5.34710753, 5.48063892, 5.59842196]])

In [23]:
np.insert(array,7,31)

array([ 30,  60,  90, 120, 150, 180, 210,  31, 240, 270])

In [24]:
np.delete(array,7)

array([ 30,  60,  90, 120, 150, 180, 210, 270])

In [25]:
np.append(array,300)

array([ 30,  60,  90, 120, 150, 180, 210, 240, 270, 300])

In [34]:
#axis = 0 untuk concatenate ke bawah
#pada posisi default axis = 0
a = np.array([[1,2],[3,4]])
print(a)
b = np.array([[9,8]])
print(b)
c=np.concatenate((a,b),axis=0)
print(c)
d=np.concatenate((a,b))
print(d)

[[1 2]
 [3 4]]
[[9 8]]
[[1 2]
 [3 4]
 [9 8]]
[[1 2]
 [3 4]
 [9 8]]


In [32]:
#axis = 1 untuk concatenate ke samping, maka array b perlu di transpose lebih dahulu
print(a)
print(b)
np.concatenate((a,b.T),axis=1)

[[1 2]
 [3 4]]
[[9 8]]


array([[1, 2, 9],
       [3, 4, 8]])

In [35]:
#axis = none untuk concatenate menjadi 1d array
print(a)
print(b)
np.concatenate((a,b),axis = None)

[[1 2]
 [3 4]]
[[9 8]]


array([1, 2, 3, 4, 9, 8])

In [36]:
np.where(array2d<150,1,array2d)

array([[  1,   1,   1],
       [  1, 150, 180],
       [210, 240, 270]])

In [37]:
np.where(array2d<150,1,0)

array([[1, 1, 1],
       [1, 0, 0],
       [0, 0, 0]])

In [39]:
np.where(array2d<=180,'Kecil','Besar')

array([['Kecil', 'Kecil', 'Kecil'],
       ['Kecil', 'Kecil', 'Kecil'],
       ['Besar', 'Besar', 'Besar']], dtype='<U5')

In [46]:
labels = ['y0','y1','y2','y3','y4']
myList = [11,22,33,44,55]
array3 = np.array(myList)
dictArray = {'y0' : 11,'y1' : 22,'y2' : 33,'y3' : 44,'y4' : 55}

#pd.Series(data,index)
print('Creating series from list')
print(pd.Series(myList))
print()
print('Creating series from list with labels')
print(pd.Series(myList,labels))
print()
print('Creating series from array with labels')
print(pd.Series(array3,labels))
print()
print('Creating series from dictionary with labels')
print(pd.Series(dictArray,labels))

Creating series from list
0    11
1    22
2    33
3    44
4    55
dtype: int64

Creating series from list with labels
y0    11
y1    22
y2    33
y3    44
y4    55
dtype: int64

Creating series from array with labels
y0    11
y1    22
y2    33
y3    44
y4    55
dtype: int64

Creating series from dictionary with labels
y0    11
y1    22
y2    33
y3    44
y4    55
dtype: int64


In [51]:
a1 = [i for i in range(1,20,3)]
b1 = [i for i in range(21,40,3)]
c1 = [i for i in range(41,60,3)]
lbl = 'a b c d e f g'
idx = 'h i j'
pd.DataFrame([a1,b1,c1],idx.split(),lbl.split())

a   b   c   d   e   f   g
h   1   4   7  10  13  16  19
i  21  24  27  30  33  36  39
j  41  44  47  50  53  56  59

In [54]:
print(pd.DataFrame(list(zip(a1,b1,c1)),lbl.split(),idx.split()))
print()
print()
#another way to reversing dimension

print(pd.DataFrame([a1,b1,c1],idx.split(),lbl.split()).T)

    h   i   j
a   1  21  41
b   4  24  44
c   7  27  47
d  10  30  50
e  13  33  53
f  16  36  56
g  19  39  59


    h   i   j
a   1  21  41
b   4  24  44
c   7  27  47
d  10  30  50
e  13  33  53
f  16  36  56
g  19  39  59


In [64]:
from numpy.random import randn
np.random.seed(101)
df = pd.DataFrame(randn(5,4),'Q W E R T'.split(),'a s d f'.split())
df

a         s         d         f
Q  2.706850  0.628133  0.907969  0.503826
W  0.651118 -0.319318 -0.848077  0.605965
E -2.018168  0.740122  0.528813 -0.589001
R  0.188695 -0.758872 -0.933237  0.955057
T  0.190794  1.978757  2.605967  0.683509

In [79]:
myd = {'a':[12,23,34,45],
       'b':[56,67,78,89],
       'c':[11,22,33,44]}
df1=pd.DataFrame(myd,'V W X Y'.split())
print(df1)

    a   b   c
V  12  56  11
W  23  67  22
X  34  78  33
Y  45  89  44


In [96]:
#adding new row with values
myd = {'a':[12,23,34,45],
       'b':[56,67,78,89],
       'c':[11,22,33,44]}
df1=pd.DataFrame(myd,'V W X Y'.split())
df1.loc['new']=[1,2,3]
df1

a   b   c
V    12  56  11
W    23  67  22
X    34  78  33
Y    45  89  44
new   1   2   3

In [91]:
#adding new columns with values
myd = {'a':[12,23,34,45],
       'b':[56,67,78,89],
       'c':[11,22,33,44]}
df1=pd.DataFrame(myd,'V W X Y'.split())
df1['new']=df1['a']+df1['c']
df1

a   b   c  new
V  12  56  11   23
W  23  67  22   45
X  34  78  33   67
Y  45  89  44   89

In [97]:
#inserting new columns with value at index [i]
myd = {'a':[12,23,34,45],
       'b':[56,67,78,89],
       'c':[11,22,33,44]}
df1=pd.DataFrame(myd,'V W X Y'.split())
df1.insert(1,'new',[4,8,12,16])
df1

a  new   b   c
V  12    4  56  11
W  23    8  67  22
X  34   12  78  33
Y  45   16  89  44

In [99]:
#removing column without inplace
myd = {'a':[12,23,34,45],
       'b':[56,67,78,89],
       'c':[11,22,33,44]}
df1=pd.DataFrame(myd,'V W X Y'.split())
df1.drop('b',axis=1)

a   c
V  12  11
W  23  22
X  34  33
Y  45  44

In [101]:
#removing column with inplace
myd = {'a':[12,23,34,45],
       'b':[56,67,78,89],
       'c':[11,22,33,44]}
df1=pd.DataFrame(myd,'V W X Y'.split())
df1.drop('b',axis=1,inplace=True)
df1

a   c
V  12  11
W  23  22
X  34  33
Y  45  44

In [102]:
#removing row
myd = {'a':[12,23,34,45],
       'b':[56,67,78,89],
       'c':[11,22,33,44]}
df1=pd.DataFrame(myd,'V W X Y'.split())
df1.drop('W',axis=0)

a   b   c
V  12  56  11
X  34  78  33
Y  45  89  44

In [105]:
#reset index to default (0,1,2,....,n)
print(df1)
df1.reset_index()

    a   b   c
V  12  56  11
W  23  67  22
X  34  78  33
Y  45  89  44


index   a   b   c
0     V  12  56  11
1     W  23  67  22
2     X  34  78  33
3     Y  45  89  44

In [106]:
newLine='BGR JKT BKS TGR'.split()
df1['Domisili'] = newLine
df1


a   b   c Domisili
V  12  56  11      BGR
W  23  67  22      JKT
X  34  78  33      BKS
Y  45  89  44      TGR

In [108]:
#penggantian index dengan newLine tanpa inplace
df1.set_index('Domisili')

a   b   c
Domisili            
BGR       12  56  11
JKT       23  67  22
BKS       34  78  33
TGR       45  89  44

In [109]:
#penggantian index dengan newLine dengan inplace
df1.set_index('Domisili',inplace=True)
df1

a   b   c
Domisili            
BGR       12  56  11
JKT       23  67  22
BKS       34  78  33
TGR       45  89  44